# Generated by Django 5.1.3 on 2025-01-24 03:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='system_config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_content', models.CharField(max_length=200)),
                ('config_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
